[package]
name = "markdown_tools"
version = "0.1.0"
edition = "2021"
description = "Tools for managing markdown formats, including aligning pipe-table columns"
license = "MIT"

[[bin]]
name = "rust-align"
path = "src/bin/rust-align.rs"

[[bin]]
name = "rust-wrap"
path = "src/bin/rust-wrap.rs"

[[bin]]
name = "rust-align-graph"
path = "src/bin/rust-align-graph.rs"

[dependencies]
unicode-width = "0.2"
